POST http://localhost:8000/places/loro-parque-tenerife/images
Content-Type: application/json

{
  "imageUrls": [
    "https://upload.wikimedia.org/wikipedia/commons/c/c1/Orcas_at_Loro_Parque_08.JPG"
  ]
}
