### 🔐 Obtener perfil actual (requiere token)
# 👇 Reemplaza con tu accessToken generado tras login
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4ODQ5NDQ5LTMzODMtNDEyNy04MzkwLTZhYjYzMTYzZjRlOSIsImlhdCI6MTc1MjMzOTAwMSwiZXhwIjoyMzU3MTM5MDAxfQ.1c5vCV4xaVc-w3sqxkPgKfhaL8TLaVFVCDr--ngAThs

GET http://localhost:8000/user/me
Authorization: Bearer {{accessToken}}


### 🗑️ Eliminar tu cuenta
DELETE http://localhost:8000/user/me
Authorization: Bearer {{accessToken}}
